name: streamlit-dashboard-example
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.6.3
  - streamlit=1.2.0
  - pandas
  - geopandas=0.3.0
  - folium=0.4.0
  - streamlit-folium-0.4.0
